language: rust
matrix:
  include:
    - rust: nightly
    - rust: stable
      env: RUSTFMT=1

    # Minimum supported Rust version
    - rust: 1.6.0
      script:
        - cargo build

before_script:
  - if [ "$RUSTFMT" = 1 ]; then rustup component add rustfmt; fi

script:
  - if [ "$RUSTFMT" = 1 ]; then cargo fmt -- --check; fi
  - cargo test
  - cargo doc --no-deps

